dist: trusty
language: rust
services: docker
sudo: required

cache:
  cargo: true
  directories:
    - $HOME/.multirust
    - $HOME/.xargo

matrix:
  include:
    - env: TARGET=aarch64-unknown-linux-gnu
      os: linux
    - env: TARGET=arm-unknown-linux-gnueabi
      os: linux
    - env: TARGET=arm-unknown-linux-gnueabihf
      os: linux
    - env: TARGET=armv7-unknown-linux-gnueabihf
      os: linux
    - env: TARGET=i586-unknown-linux-gnu
      os: linux
    - env: TARGET=i686-apple-darwin
      os: osx
    - env: TARGET=i686-unknown-linux-gnu
      os: linux
    - env: TARGET=mips-unknown-linux-gnu
      os: linux
    - env: TARGET=mipsel-unknown-linux-gnu
      os: linux
    - env: TARGET=powerpc-unknown-linux-gnu
      os: linux
    - env: TARGET=powerpc64-unknown-linux-gnu
      os: linux
    - env: TARGET=powerpc64le-unknown-linux-gnu
      os: linux
    - env: TARGET=thumbv6m-none-eabi
      os: linux
    - env: TARGET=thumbv7em-none-eabi
      os: linux
    - env: TARGET=thumbv7m-none-eabi
      os: linux
    - env: TARGET=x86_64-apple-darwin
      os: osx
    - env: TARGET=x86_64-unknown-linux-gnu
      os: linux

before_install:
  - export PATH="$PATH:$HOME/.cargo/bin"

install:
  - bash ci/install.sh

script:
  - bash ci/script.sh

notifications:
  email:
    on_success: never
